spring:
  datasource:
    url: jdbc:postgresql://raspberrypi.local:5432/plantmanagerdb
    username: postgres
    password: password

  jpa:
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true
    defer-datasource-initialization: false